### ISSUE TITLE
line 1, in <module>     import pygame ModuleNotFoundError: No module named 'pygame'

### ISSUE THREAD

**Issue by LeonSeigi** [codegiovanni/Donut#2]
line 1, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

I try your donut.py by copy the code but there is an error so I can run it. How to solve the problem?

**Comment by damullutkid** [comment]
you must install pygame first using pip, you should be able to search it up on google

**Comment by LeonSeigi** [comment]
@damullutkid Thank you for answered my problem😃👍
